[package]
name = "easymanage-agent"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
easymanage-protocol = { path = "../protocol" }
easymanage-runtime = { path = "../runtime" }

[lints]
workspace = true
